export const GAME = {
  maxPlayers: 10,
  maxHealth: 100,
  maxArmor: 50,
  roundsToWin: 13,
  maxOvertimeRounds: 6,
  tickRate: 60,
  snapshotRate: 20,
  buyPhaseSeconds: 15,
  roundSeconds: 120,
  intermissionSeconds: 5,
  plantSeconds: 4,
  defuseSeconds: 5,
  deviceSeconds: 35,
  mapBounds: 42,
  playerRadius: 0.42,
  movementSpeed: 7,
  sprintMultiplier: 1.35,
  walkMultiplier: 0.65,
  crouchMultiplier: 0.5,
} as const;
